### PR TITLE
Update subdomains SQL template asset

### PR DESCRIPTION
**Pull request by cqsd**
The SQL template for getting subdomains from HTTP Archive was patched in https://github.com/assetnote/commonspeak2/pull/8, but the respective asset was not updated. Fresh builds at this time still use the old template.

This PR updates `assets/assets.go` with the new template. The diff was produced by running:
```
go-bindata -pkg assets -o assets/assets.go data/...
go fmt ./assets/...
```

More context: https://github.com/assetnote/commonspeak2/issues/7#issuecomment-620421781

### CODE REVIEW

**Comment by Techbrunch** [comment]
I also ran into this issue, any chance we can merge this and create a new release ? ping @infosec-au

**Comment by infosec-au** [comment]
Thanks @Techbrunch for the fix. Sorry it took so long for me to get to this.

**Comment by Techbrunch** [comment]
> Thanks @Techbrunch for the fix. Sorry it took so long for me to get to this.

You should thank @cqsd but I'm glad it got fixed :)

**Comment by infosec-au** [comment]
Thank you @cqsd! Absolute legend!

**Pull request merged**
